services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"   # Mapping du port MySQL pour permettre la connexion externe
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./config/db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
